aoiVersion: v1
kind: Service
metadata:
  name: k8s-static-svc
  namespace: static
spec:
  selector:
    app: static
  ports:
    - protocal: TCP
      ports: 80
      targetPort: 80
  type: LoadBalancer
